apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
spec:
  selector:
    matchLabels:
      app: caddy
  replicas: 2
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
